url: 'vaporware.network'
baseurl: ''
title: 'VAPORWARE'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock

defaults:
  - scope:
      type: "pages"
      path: "_layouts/blog"
    values:
      hide_nav: true

permalink: pretty